java.lang.NullPointerException: Cannot read field "state" because the return value of "java.util.Map.get(Object)" is null 	at org.swisspush.redisques.RedisQues.lambda$consume$36(RedisQues.java:1007) ~[redisques-4.1.13.jar:?] 	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176) ~[vertx-core-4.5.1.jar:4.5.1] 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66) ~[vertx-core-4.5.1.jar:4.5.1]